
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: my-fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - UVICORN_WORKERS=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: my-react-app-dev
    container_name: react-app-dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=3000
      - REACT_APP_API_URL=http://fastapi:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app:cached
      - frontend_node_modules:/usr/src/app/node_modules
    networks:
      - app-network

volumes:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge
