
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: my-fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - UVICORN_WORKERS=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: my-react-app
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
